<?php
/**
 * FaxReceivingApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Fax.to REST API client for PHP
 *
 * This is Fax.to REST API client for PHP.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * FaxReceivingApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FaxReceivingApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for areaCodesCountryCodeStateIdGet
     *
     * This API gets a list of countries with its area code.
     *
     */
    public function testAreaCodesCountryCodeStateIdGet()
    {
    }

    /**
     * Test case for countriesCountryCodeDidGroupsGet
     *
     * This API gets a list of DID groups.
     *
     */
    public function testCountriesCountryCodeDidGroupsGet()
    {
    }

    /**
     * Test case for countriesGet
     *
     * This API gets a list of countries available in the Fax.to coverage.
     *
     */
    public function testCountriesGet()
    {
    }

    /**
     * Test case for incomingFaxesGet
     *
     * This API gets a list of incoming faxes.
     *
     */
    public function testIncomingFaxesGet()
    {
    }

    /**
     * Test case for incomingFaxesRecipientGet
     *
     * This API gets a list of incoming faxes for a specific recipient.
     *
     */
    public function testIncomingFaxesRecipientGet()
    {
    }

    /**
     * Test case for numbersGet
     *
     * This API gets a list of numbers to get the current configuration of one or multiple number.
     *
     */
    public function testNumbersGet()
    {
    }

    /**
     * Test case for provisionNumbersGet
     *
     * This API gets a list of provisioned numbers.
     *
     */
    public function testProvisionNumbersGet()
    {
    }

    /**
     * Test case for statesCountryCodeGet
     *
     * This API gets a list of states of a given country available in the Fax.to coverage.
     *
     */
    public function testStatesCountryCodeGet()
    {
    }
}
