<?php
/**
 * FaxSendingApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Fax.to REST API client for PHP
 *
 * This is Fax.to REST API client for PHP.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * FaxSendingApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FaxSendingApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for faxDocumentIdCostsGet
     *
     * This API is for computing the cost of the fax to be sent.
     *
     */
    public function testFaxDocumentIdCostsGet()
    {
    }

    /**
     * Test case for faxHistoryGet
     *
     * This API gets the history of a fax.
     *
     */
    public function testFaxHistoryGet()
    {
    }

    /**
     * Test case for faxJobIdStatusGet
     *
     * This API gets the status of a fax.
     *
     */
    public function testFaxJobIdStatusGet()
    {
    }

    /**
     * Test case for faxPost
     *
     * This API is for sending a new fax in any fax numbers anywhere in the world.
     *
     */
    public function testFaxPost()
    {
    }

    /**
     * Test case for fileCleanGet
     *
     * This API is used for cleaning a document.
     *
     */
    public function testFileCleanGet()
    {
    }

    /**
     * Test case for fileGeneratePreviewGet
     *
     * This API generates a preview of a document.
     *
     */
    public function testFileGeneratePreviewGet()
    {
    }

    /**
     * Test case for filesDocumentIDDelete
     *
     * This API deletes a document.
     *
     */
    public function testFilesDocumentIDDelete()
    {
    }

    /**
     * Test case for filesGet
     *
     * This API gets all the files of a certain user.
     *
     */
    public function testFilesGet()
    {
    }
}
