<?php
/**
 * InlineResponse2009Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Fax.to REST API client for PHP
 *
 * This is Fax.to REST API client for PHP.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InlineResponse2009Test Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse2009
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse2009Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse2009"
     */
    public function testInlineResponse2009()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {
    }

    /**
     * Test attribute "created_date"
     */
    public function testPropertyCreatedDate()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "filename"
     */
    public function testPropertyFilename()
    {
    }

    /**
     * Test attribute "orig_filename"
     */
    public function testPropertyOrigFilename()
    {
    }

    /**
     * Test attribute "preview_file"
     */
    public function testPropertyPreviewFile()
    {
    }

    /**
     * Test attribute "preview_image"
     */
    public function testPropertyPreviewImage()
    {
    }

    /**
     * Test attribute "preview_in_storage"
     */
    public function testPropertyPreviewInStorage()
    {
    }

    /**
     * Test attribute "file_extension"
     */
    public function testPropertyFileExtension()
    {
    }

    /**
     * Test attribute "filename_uploaded"
     */
    public function testPropertyFilenameUploaded()
    {
    }

    /**
     * Test attribute "filesize"
     */
    public function testPropertyFilesize()
    {
    }

    /**
     * Test attribute "s3"
     */
    public function testPropertyS3()
    {
    }

    /**
     * Test attribute "server_document_id"
     */
    public function testPropertyServerDocumentId()
    {
    }

    /**
     * Test attribute "team_user_id"
     */
    public function testPropertyTeamUserId()
    {
    }

    /**
     * Test attribute "total_pages"
     */
    public function testPropertyTotalPages()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }
}
